
package Form;
import java.sql.*; 
import javax.swing.JOptionPane; 
import javax.swing.table.DefaultTableModel; 
import Koneksi.koneksi;
import java.awt.event.KeyEvent;

public class Kasir extends javax.swing.JFrame {
private Connection conn = new koneksi().connect(); 
private DefaultTableModel tabmode;
    
    public Kasir() {
        initComponents();
        kosong(); 
        aktif(); 
        datatable();
    }
    
    protected void aktif () { 
        txtidk.requestFocus(); 
    } 
    protected void kosong() { 
        txtidk.setText(""); 
        txtnmk.setText(""); 
        txttelpk.setText("");
        txtalmk.setText("");
        txtcarik.setText("");
        buttonGroup1.clearSelection();
    }

    protected void datatable() { 
        Object[] Baris ={"ID Kasir", "Nama", "Jenis Kelamin", "No. Telepon", "Agama","Alamat","Password"}; 
            tabmode = new DefaultTableModel (null, Baris); 
            //tablebarang.setModel(tabmode); 
            String cariitem=txtcarik.getText();
            
            try { 
            String sql = "select * from kasir1 where idkasir like '%"+cariitem+"%' or nmkasir like '%"+cariitem+"%' order by idkasir asc";
            Statement stat = conn.createStatement(); 
            ResultSet hasil = stat.executeQuery(sql); 
            while (hasil.next()) { 
                tabmode.addRow (new Object[]{ 
                    hasil.getString(1), 
                    hasil.getString(2), 
                    hasil.getString(3), 
                    hasil.getString(4), 
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7) 
                }); 
            }
            tblplgnk.setModel(tabmode); 
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(null, "data gagal dipanggil"+e);
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtidk = new javax.swing.JTextField();
        txtnmk = new javax.swing.JTextField();
        rlakik = new javax.swing.JRadioButton();
        rperempuank = new javax.swing.JRadioButton();
        txtagama = new javax.swing.JTextField();
        txttelpk = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalmk = new javax.swing.JTextArea();
        txtpw = new javax.swing.JPasswordField();
        bsimpank = new javax.swing.JButton();
        bubahk = new javax.swing.JButton();
        bhapusk = new javax.swing.JButton();
        bbatalk = new javax.swing.JButton();
        bkeluark = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtcarik = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblplgnk = new javax.swing.JTable();
        bcarik = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel1.setText("DATA KASIR");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, 50));

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel2.setText("ID Kasir");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, -1, 30));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel3.setText("Nama Kasir");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, -1, 30));

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel4.setText("Jenis Kelamin");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, 30));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel5.setText("Agama");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, -1, 30));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel6.setText("No Telepon");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, 30));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel7.setText("Alamat");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 30));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jLabel8.setText("Password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, -1, 30));

        txtidk.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        getContentPane().add(txtidk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 228, 30));

        txtnmk.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        getContentPane().add(txtnmk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 228, 30));

        rlakik.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        rlakik.setText("Laki-Laki");
        rlakik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rlakikActionPerformed(evt);
            }
        });
        getContentPane().add(rlakik, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, -1, 30));

        rperempuank.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        rperempuank.setText("Perempuan");
        getContentPane().add(rperempuank, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, 30));

        txtagama.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtagama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtagamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtagama, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 228, 30));

        txttelpk.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        getContentPane().add(txttelpk, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 228, 30));

        txtalmk.setColumns(20);
        txtalmk.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtalmk.setRows(5);
        jScrollPane1.setViewportView(txtalmk);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 260, 228, 90));

        txtpw.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        getContentPane().add(txtpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 228, 30));

        bsimpank.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bsimpank.setText("Simpan");
        bsimpank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpankActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpank, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        bubahk.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bubahk.setText("Ubah");
        bubahk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bubahkActionPerformed(evt);
            }
        });
        getContentPane().add(bubahk, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 70, -1));

        bhapusk.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bhapusk.setText("Hapus");
        bhapusk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapuskActionPerformed(evt);
            }
        });
        getContentPane().add(bhapusk, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 410, 70, -1));

        bbatalk.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bbatalk.setText("Batal");
        bbatalk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalkActionPerformed(evt);
            }
        });
        getContentPane().add(bbatalk, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 410, 70, -1));

        bkeluark.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bkeluark.setText("Keluar");
        bkeluark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarkActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluark, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 410, 70, -1));

        jLabel9.setFont(new java.awt.Font("Poppins", 1, 11)); // NOI18N
        jLabel9.setText("Data Kasir");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, -1));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcarik.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        txtcarik.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcarikKeyPressed(evt);
            }
        });
        jPanel2.add(txtcarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 13, 108, -1));

        tblplgnk.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tblplgnk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgnk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplgnkMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblplgnk);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 45, 450, 140));

        bcarik.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bcarik.setText("Cari");
        bcarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcarikActionPerformed(evt);
            }
        });
        jPanel2.add(bcarik, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 12, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 200));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        setSize(new java.awt.Dimension(518, 736));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rlakikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rlakikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rlakikActionPerformed

    private void tblplgnkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnkMouseClicked
        int bar = tblplgnk.getSelectedRow(); 
        String a = tabmode.getValueAt(bar, 0).toString(); 
        String b = tabmode.getValueAt(bar, 1).toString(); 
        String c = tabmode.getValueAt(bar, 2).toString(); 
        String d = tabmode.getValueAt(bar, 3).toString(); 
        String e = tabmode.getValueAt(bar, 4).toString(); 
        String f = tabmode.getValueAt(bar, 5).toString(); 
        String g = tabmode.getValueAt(bar, 6).toString(); 
        
        txtidk.setText(a); 
        txtnmk.setText(b); 
        
        if ("Laki-Laki".equals(c)) { 
            rlakik.setSelected(true); 
            } else{ 
            rperempuank.setSelected(true); 
            } 
        txttelpk.setText(d); 
        txtagama.setText(e);
        txtalmk.setText(f);
        txtpw.setText(g);
    }//GEN-LAST:event_tblplgnkMouseClicked

    private void bsimpankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpankActionPerformed
        String jenis = null;
        if (rlakik.isSelected()) {
            jenis = "Laki-Laki";
        }else if (rperempuank.isSelected()) {
            jenis = "Perempuan";
        }
        String sql = "insert into kasir values (?,?,?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtidk.getText());
            stat.setString(2, txtnmk.getText());
            stat.setString(3, jenis);
            stat.setString(4, txttelpk.getText());
            stat.setString(5, txtagama.getText());
            stat.setString(6, txtalmk.getText());
            stat.setString(7, txtpw.getText());

            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            txtidk.requestFocus();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable(); 
    }//GEN-LAST:event_bsimpankActionPerformed

    private void bubahkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bubahkActionPerformed
        String jenis = null;
        if (rlakik.isSelected()) {
            jenis = "Laki-Laki";
        }else if (rperempuank.isSelected()) {
            jenis = "Perempuan";
        }

        try{
            String sql = "update kasir set nmkasir=?,jenis=?,telepon=?,agama=?,alamat=?,Password=? where idkasir='"+txtidk.getText()+"'";
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtnmk.getText());
            stat.setString(2, jenis);
            stat.setString(3, txttelpk.getText());
            stat.setString(4, txtagama.getText());
            stat.setString(5, txtalmk.getText());
            stat.setString(6, txtpw.getText());


            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            txtidk.requestFocus();
        }
        catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah"+e);
        }
        datatable();
    }//GEN-LAST:event_bubahkActionPerformed

    private void bhapuskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapuskActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        if (ok==0) {
            String sql = "delete from kasir where idkasir ='"+txtidk.getText()+"'";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                txtidk.requestFocus();
            }
            catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus"+e);
            }
            datatable();
        }
    }//GEN-LAST:event_bhapuskActionPerformed

    private void bbatalkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalkActionPerformed
        kosong();
        datatable();
    }//GEN-LAST:event_bbatalkActionPerformed

    private void bkeluarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarkActionPerformed
        dispose();
    }//GEN-LAST:event_bkeluarkActionPerformed

    private void txtagamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtagamaActionPerformed

    private void txtcarikKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcarikKeyPressed
        // TODO add your handling code here:
                if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
            datatable(); 
        }
    }//GEN-LAST:event_txtcarikKeyPressed

    private void bcarikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcarikActionPerformed
        // TODO add your handling code here:
        datatable();
    }//GEN-LAST:event_bcarikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kasir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kasir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatalk;
    private javax.swing.JButton bcarik;
    private javax.swing.JButton bhapusk;
    private javax.swing.JButton bkeluark;
    private javax.swing.JButton bsimpank;
    private javax.swing.JButton bubahk;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rlakik;
    private javax.swing.JRadioButton rperempuank;
    private javax.swing.JTable tblplgnk;
    private javax.swing.JTextField txtagama;
    private javax.swing.JTextArea txtalmk;
    private javax.swing.JTextField txtcarik;
    private javax.swing.JTextField txtidk;
    private javax.swing.JTextField txtnmk;
    private javax.swing.JPasswordField txtpw;
    private javax.swing.JTextField txttelpk;
    // End of variables declaration//GEN-END:variables
}
