

package Form;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JSpinner;
import Koneksi.koneksi;

public class Nota extends javax.swing.JFrame {
    public String id, nama, jenis, telp, almt;
    public String kdbrg, nmbrg, jenisbrg, hb, hj;
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;



    public Nota() {
        initComponents();
        String KD = UserID.getUserLogin();
        jLabel17.setText(KD);
        kosong();
        aktif();
        autonumber();
        nama();
    }

    protected void nama(){
    try {
        String sql = "SELECT * FROM kasir WHERE idkasir='" + jLabel17.getText() + "'";
        Statement stat = conn.createStatement();
        ResultSet hasil = stat.executeQuery(sql);
        while(hasil.next()){
            jLabel18.setText(hasil.getString("nmkasir"));
        }
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal dipanggil" + e);
    }
}
    
    protected void aktif(){
        txtqty.requestFocus();
        jtgl.setEditor(new JSpinner.DateEditor(jtgl,"yyyy/MM/dd"));
        Object[] Baris = {"KD Barang", "Nama", "Harga Beli", "Harga Jual", "QTY", "Total"};
        tabmode = new DefaultTableModel(null, Baris);
        tbltransaksi.setModel(tabmode);
    }
    
    protected void kosong(){
        txtid.setText("");
        txtnm.setText("");
        txtalmt.setText("");
        txtkdbrg.setText("");
        txtnmbrg.setText("");
        txthb.setText("");
        txthj.setText("");
        txtqty.setText("");
        txttotal.setText("");
    }
    
    protected void autonumber(){
    try {
        String sql = "SELECT id_nota FROM nota order by id_nota asc";
        Statement st = conn.createStatement();
        ResultSet rs = st.executeQuery(sql);
        txtidnota.setText("IN0001");
        while (rs.next()) {
            String id_nota = rs.getString("id_nota").substring(2);
            int AN = Integer.parseInt(id_nota) + 1;
            String NoI = "";

            if (AN < 10) {
                NoI = "000";
            } else if (AN < 100) {
                NoI = "00";
            } else if (AN < 1000) {
                NoI = "0";
            } else if (AN < 10000) {
                NoI = "";
            }

            txtidnota.setText("IN" + NoI + AN);
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Auto Number Gagal" + e);
    }
}

    public void itemTerpilih(){
    popuppelanggan Pp = new popuppelanggan();
    Pp.plgn = this;
    txtid.setText(id);
    txtnm.setText(nama);
    txtalmt.setText(almt);
}

    public void itemTerpilihBrg(){
    popupbarang Pbrg = new popupbarang();
    Pbrg.brg = this;
    txtkdbrg.setText(kdbrg);
    txtnmbrg.setText(nmbrg);
    txthb.setText(hb);
    txthj.setText(hj);
    txtqty.requestFocus();
    }
    
    public void hitung(){
    int total = 0;
    for (int i = 0; i < tbltransaksi.getRowCount(); i++){
        int amount = Integer.valueOf(tbltransaksi.getValueAt(i, 5).toString());
        total += amount;
    }
    txttotal.setText(Integer.toString(total));
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        txtnm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalmt = new javax.swing.JTextArea();
        txtid = new javax.swing.JTextField();
        bcarip = new javax.swing.JButton();
        jtgl = new javax.swing.JSpinner();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        btambah = new javax.swing.JButton();
        txtkdbrg = new javax.swing.JTextField();
        txtnmbrg = new javax.swing.JTextField();
        txthb = new javax.swing.JTextField();
        txthj = new javax.swing.JTextField();
        txtqty = new javax.swing.JTextField();
        bcaribrg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtidnota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltransaksi = new javax.swing.JTable();
        bhapus = new javax.swing.JButton();
        bkeluar = new javax.swing.JButton();
        bsimpan = new javax.swing.JButton();
        bbatal = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtttotal = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(710, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Pelanggan", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 11))); // NOI18N
        jPanel2.setToolTipText("");
        jPanel2.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jPanel2.setName("Data Pelanggan"); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtnm.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jPanel2.add(txtnm, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 200, -1));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel1.setText("Alamat");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel7.setText("ID Pelanggan");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel8.setText("Nama");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        txtalmt.setColumns(20);
        txtalmt.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        txtalmt.setRows(5);
        jScrollPane1.setViewportView(txtalmt);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 200, 110));

        txtid.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jPanel2.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 130, -1));

        bcarip.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bcarip.setText("Cari");
        bcarip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaripActionPerformed(evt);
            }
        });
        jPanel2.add(bcarip, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 60, 20));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 330, 250));
        jPanel2.getAccessibleContext().setAccessibleName("");

        jtgl.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jtgl.setModel(new javax.swing.SpinnerDateModel());
        jtgl.setToolTipText("");
        getContentPane().add(jtgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 130, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Data Barang", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 11))); // NOI18N
        jPanel3.setToolTipText("");
        jPanel3.setName("Data Pelanggan"); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel2.setText("Total");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        txttotal.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jPanel3.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 190, -1));

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel10.setText("KD Barang");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 20));

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel11.setText("Nama");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, 20));

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel12.setText("Harga Beli");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 20));

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel13.setText("Harga Jual");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, 20));

        jLabel14.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel14.setText("QTY");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, 20));

        btambah.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        btambah.setText("Tambah");
        btambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btambahActionPerformed(evt);
            }
        });
        jPanel3.add(btambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 250, -1));

        txtkdbrg.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jPanel3.add(txtkdbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 130, -1));

        txtnmbrg.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jPanel3.add(txtnmbrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 190, -1));

        txthb.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jPanel3.add(txthb, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, 190, -1));

        txthj.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jPanel3.add(txthj, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 190, -1));

        txtqty.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        txtqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqtyActionPerformed(evt);
            }
        });
        txtqty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtqtyKeyReleased(evt);
            }
        });
        jPanel3.add(txtqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 190, -1));

        bcaribrg.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bcaribrg.setText("Cari");
        bcaribrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcaribrgActionPerformed(evt);
            }
        });
        jPanel3.add(bcaribrg, new org.netbeans.lib.awtextra.AbsoluteConstraints(215, 30, -1, 20));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 290, 250));

        jLabel3.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel3.setText("Total Harga");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 680, -1, 20));

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("NOTA");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 710, 30));

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel5.setText("Nama Kasir :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, -1, 20));

        txtidnota.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        getContentPane().add(txtidnota, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 110, -1));

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel6.setText("ID Nota");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 20));

        jLabel9.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel9.setText("Nama Kasir");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, 30));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Poppins", 0, 11))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbltransaksi.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        tbltransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbltransaksi);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 590, 150));

        bhapus.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        bhapus.setText("Hapus");
        bhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bhapusActionPerformed(evt);
            }
        });
        jPanel4.add(bhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 190, 70, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 630, 230));

        bkeluar.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        bkeluar.setText("Keluar");
        bkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkeluarActionPerformed(evt);
            }
        });
        getContentPane().add(bkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 670, 80, 30));

        bsimpan.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        bsimpan.setText("Simpan");
        bsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(bsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 670, -1, 30));

        bbatal.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        bbatal.setText("Batal");
        bbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbatalActionPerformed(evt);
            }
        });
        getContentPane().add(bbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, 80, 30));

        jLabel16.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel16.setText("ID Kasir :");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, -1, 20));
        getContentPane().add(txtttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 680, 120, 20));

        jLabel17.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel17.setText("jLabel17");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 100, 20));

        jLabel18.setFont(new java.awt.Font("Poppins", 0, 10)); // NOI18N
        jLabel18.setText("jLabel18");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 110, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btambahActionPerformed
        // TODO add your handling code here:
        try {
    String kode = txtkdbrg.getText();
    String nama = txtnmbrg.getText();
    int hargab = Integer.parseInt(txthb.getText());
    int hargaj = Integer.parseInt(txthj.getText());
    int qty = Integer.parseInt(txtqty.getText());
    int total = hargaj * qty;
    hitung();
    tabmode.addRow(new Object[]{kode, nama, hargab, hargaj, qty, total});
    tbltransaksi.setModel(tabmode);
    
    } catch (Exception e) {
        System.out.println("Error : " + e);
    }
    txtkdbrg.setText("");
    txtnmbrg.setText("");
    txthb.setText("");
    txthj.setText("");
    txtqty.setText("");
    txttotal.setText("");
        
    }//GEN-LAST:event_btambahActionPerformed

    private void bcaripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaripActionPerformed
        // TODO add your handling code here:
    popuppelanggan Pplgn = new popuppelanggan();
    Pplgn.plgn = this;
    Pplgn.setVisible(true);
    Pplgn.setResizable(false);
    }//GEN-LAST:event_bcaripActionPerformed

    private void bcaribrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcaribrgActionPerformed
        // TODO add your handling code here:
    popupbarang Pbrg = new popupbarang();
    Pbrg.brg = this;
    Pbrg.setVisible(true);
    Pbrg.setResizable(false);
    }//GEN-LAST:event_bcaribrgActionPerformed

    private void txtqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqtyActionPerformed
        // TODO add your handling code here:                                
    int xhrgj = Integer.parseInt(txthj.getText());
    int xqty = Integer.parseInt(txtqty.getText());
    int xjml = xhrgj * xqty;
    
    txttotal.setText(String.valueOf(xjml));
   
    }//GEN-LAST:event_txtqtyActionPerformed

    private void bhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bhapusActionPerformed
        // TODO add your handling code here:
        try{
        int index = tbltransaksi.getSelectedRow();
        tabmode.removeRow(index);
        tbltransaksi.setModel(tabmode);
        hitung();
        txttotal.setText("");
        
        }catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Pilih Kolom Terlebih Dahulu" + e);
    }
    }//GEN-LAST:event_bhapusActionPerformed

    private void bsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsimpanActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String fd = sdf.format(jtgl.getValue());
        String sql = "insert into nota values (?,?,?,?)";
        String zsql = "insert into isi values (?,?,?,?,?)";
try {
    PreparedStatement stat = conn.prepareStatement(sql);
    stat.setString(1, txtidnota.getText());
    stat.setString(2, fd);
    stat.setString(3, txtid.getText());
    stat.setString(4, jLabel17.getText());
    stat.executeUpdate();

    int t = tbltransaksi.getRowCount();
    for (int i = 0; i < t; i++) {
        String xkd = tbltransaksi.getValueAt(i, 0).toString();
        String xhb = tbltransaksi.getValueAt(i, 2).toString();
        String xhj = tbltransaksi.getValueAt(i, 3).toString();
        String xqty = tbltransaksi.getValueAt(i, 4).toString();

        PreparedStatement stat2 = conn.prepareStatement(zsql);
        stat2.setString(1, txtidnota.getText());
        stat2.setString(2, xkd);
        stat2.setString(3, xhb);
        stat2.setString(4, xhj);
        stat2.setString(5, xqty);
        stat2.executeUpdate();
    }
        JOptionPane.showMessageDialog(null, "Data berhasil disimpan");
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(null, "Data gagal disimpan" + e);
    }

        kosong();
        aktif();
        autonumber();
    }//GEN-LAST:event_bsimpanActionPerformed

    private void bbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbatalActionPerformed
        // TODO add your handling code here:
        kosong();
        aktif();
        autonumber();
    }//GEN-LAST:event_bbatalActionPerformed

    private void bkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkeluarActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_bkeluarActionPerformed

    private void txtqtyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqtyKeyReleased
        // TODO add your handling code here:
        try {
        int xhrgj = Integer.parseInt(txthj.getText());
        int xqty = Integer.parseInt(txtqty.getText());
        int xjml = xhrgj * xqty;
        txttotal.setText(String.valueOf(xjml));
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Input salah, pastikan angka yang dimasukkan valid.");
    }
    }//GEN-LAST:event_txtqtyKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nota().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bbatal;
    private javax.swing.JButton bcaribrg;
    private javax.swing.JButton bcarip;
    private javax.swing.JButton bhapus;
    private javax.swing.JButton bkeluar;
    private javax.swing.JButton bsimpan;
    private javax.swing.JButton btambah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jtgl;
    private javax.swing.JTable tbltransaksi;
    private javax.swing.JTextArea txtalmt;
    private javax.swing.JTextField txthb;
    private javax.swing.JTextField txthj;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtidnota;
    private javax.swing.JTextField txtkdbrg;
    private javax.swing.JTextField txtnm;
    private javax.swing.JTextField txtnmbrg;
    private javax.swing.JTextField txtqty;
    private javax.swing.JTextField txttotal;
    private javax.swing.JTextField txtttotal;
    // End of variables declaration//GEN-END:variables

}
